import os
from dotenv import load_dotenv


load_dotenv()


AUTH_TOKEN = os.getenv('AUTH_TOKEN')
LIFETIME = os.getenv('LIFETIME')

DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_PASS = os.getenv('DATABASE_PASSWORD')
DATABASE_HOST = os.getenv('DATABASE_HOST')
DATABASE_PORT = os.getenv('DATABASE_PORT')
DATABASE_NAME = os.getenv('DATABASE_NAME')

DATABASE_CREDENTIALS = f'{DATABASE_USER}:{DATABASE_PASS}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}'
ASYNC_DATABASE_URL = 'postgresql+asyncpg://' + DATABASE_CREDENTIALS
SYNC_DATABASE_URL = 'postgresql+psycopg2://' + DATABASE_CREDENTIALS

REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT_CACHE = os.getenv('REDIS_PORT_CACHE')
REDIS_PORT_CELERY = os.getenv('REDIS_PORT_CELERY')
